apiVersion: apps/v1
kind: Deployment
metadata:
  name: nineops-agent
spec:
  selector:
    matchLabels:
      app: nineops-agent
  template:
    metadata:
      labels:
        app: nineops-agent
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: nineops-agent
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
      - name: nineops-agent
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: nineops-agent-config
        ports:
        - containerPort: 8081
          protocol: TCP
          name: http-metrics
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
          - mountPath: "/etc/backend/ssl"
            name: nineops-cert-volume
            readOnly: true
      volumes:
      - name: nineops-cert-volume
        secret:
          secretName: nineops-client-secret
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
