apiVersion: v1
kind: Secret
metadata:
  name: nineops-client-secret
  namespace: default
type: kubernetes.io/tls
data:
  ca.crt: {{ required "cacrt required" .Values.settings.cert.cacrt }}
  tls.crt: {{ required "tlscrt" .Values.settings.cert.tlscrt }}
  tls.key: {{ required "tlskey required" .Values.settings.cert.tlskey }}