{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nineops-agent-metrics
  labels:
    app: nineops-agent
spec:
  ports:
  - name: http-metrics
    port: {{ .Values.metrics.service.port }}
    targetPort: 8081
  type: {{ .Values.metrics.service.type }}
  selector:
    app: nineops-agent
{{- end }}
